#!/usr/bin/python3
# SPDX-FileCopyRightText: 2024 Shota Kaneko
# SPDX-License-Identifier: BSD-3-Clause

import sys


un = 0
chin = 0
ko = 1
nyo = []

for ama in sys.stdin:
    k = int(ama.strip())
if (k > 0 and k < 20577):
    nyo.append(1)
    for i in range(1, k):
        chin = un + ko
        un = ko
        ko = chin
        nyo.append(chin)

print(*nyo)

if (k > 20576):
    print("もっと少ない数を入力してください")
