#!/usr/bin/python3
# SPDX-FileCopyfightText: 2024 Shota kaneko

import sys

ans = 0
for line in sys.stdin:
    line = line.rstrip()
    try:
        ans += int(line)
    except:
        ans += float(line)

print(ans)
